### PR TITLE
Honor map key comparison semantics with `containsOnly` assertions

### LINKED ISSUE #2159: Map `containsOnly` assertions don't work correctly with case insensitive keys
#### Summary

When using case insensitive maps the map assertions for containsOnly are not working correctly.
The reason for this is due to the fact that the actual map is copied into a `LinkedHashMap` and thus the checks are not using the map.

#### Example

```java
Map<String, String> map = new LinkedCaseInsensitiveMap<>();
map.put("TEST", "value");
```

The following assertions will pass
```java
assertThat(map).containsKey("test");
assertThat(map).contains(entry("test", "value"));
```

The following assertions will fail
```java
assertThat(map).containsOnlyKeys("test");
assertThat(map).containsOnly(entry("test", "value"));
```

Note: `LinkedCaseInsensitiveMap` is from Spring.

If you agree I can work on a PR to change the mechanism that is used for validating `containsOnly` entries.

### PR DESCRIPTION
**Pull request by joel-costigliola**
This affects:
- `assertContainsOnly`
- `assertContainsOnlyKeys`

#### Open points:
- [x] Complete `Maps_assertContainsOnlyKeys_Test`
- [x] Complete `Maps_assertContainsOnly_Test`
- [x] Evaluate refactoring of `assertDoesNotContainKeys(AssertionInfo, Map, Object[])`
- [x] Mention in the javadoc that in some cases the key comparison semantics won't be honored

#### Check List:
* Fixes #2159
* Unit tests : YES
* Javadoc with a code example (on API only) : NA
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

### CODE REVIEW

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 1]
```diff
@@ -827,12 +833,24 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
     notExpected.addAll(actualEntries.keySet());
   }
 
+  private <V, K> Map<K, V> instantiate(Class<? extends Map> mapClass) {
+    try {
+      Constructor<?> constructor = mapClass.getConstructor();
+      return (Map<K, V>) constructor.newInstance();
+      // return objenesis.newInstance(class1);
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/internal/Maps.java:840]: I have setup objenesis, uncomment to see the error we have when using it

**Comment by joel-costigliola** [comment]
@filiphr feel free to review and contribute to this PR if you have time, this one supersedes https://github.com/assertj/assertj-core/pull/2160.

**Comment by joel-costigliola** [comment]
The build fails due to too many lib to shade, not a blocker right now for us to play with objenesis

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 1 above)
Comment (joel-costigliola) [reply src/main/java/org/assertj/core/internal/Maps.java:840]: We should create an `InstantiatorStrategy` with different implementation instead of this basic approach.

**Comment by filiphr** [comment]
I am not sure that using `Objenesis` or even creating a copy of the map should be the way forward. At least not for all maps.

Have a look at my additional test cases in https://github.com/filiphr/assertj-core/commit/96360d786af5948a887ab23a2ac92749921752b2. Using `Collections.unmodifiableMap` works, using Guava immutable map works as well. Using `SingletonMap` doesn't work.

A potential (not 100% cases solution) would be to only create a copy if the map is a case insensitive map. e.g. like in https://github.com/filiphr/assertj-core/commit/d7a77b9db070797a12e744ad7a2b687b606ad60b.

**Comment by joel-costigliola** [comment]
thanks for fixing the pom @scordio.

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 1 above)
Comment (goughy000) [reply src/main/java/org/assertj/core/internal/Maps.java:840]: Just a thought - perhaps trying a `clone()` if the class implements `Cloneable` could be one of the implementations of `InstantiatorStrategy`.  `java.util.HashMap` implements this, so it's likely to be common

**Comment by scordio** [comment]
I try to summarize the topic to see if I got it correctly.

The `containsOnly` / `containsExactly` assertions consist of two steps:
1. Checking if the expected elements are present
2. Finding the unexpected ones

Elements can be either keys or entries depending on the specific assertion.

### Checking the expected elements

The check should always be performed on `actual` to honor the original semantic.

This is mostly relevant with special implementations like `org.apache.commons.collections4.map.CaseInsensitiveMap` or `org.springframework.util.LinkedCaseInsensitiveMap`.

### Finding of unexpected elements

In the ideal case, we want to have a copy of the map and remove the expected elements, so what is left are the unexpected elements.

Being able to do this strongly depends on the map implementation.

1. #### `Cloneable` implementation
    A new instance can be obtained via `clone()`, then we try to `remove()` the expected elements
    * `remove` succeeds &#8594; unexpected elements are identified
    * `remove` fails with `UnsupportedOperationException`, (i.e., unmodifiable) &#8594; new `LinkedHashMap` initialized with the elements of `actual`, `remove()` is repeated again &#8594;  unexpected elements are identified but with the potential loss of the original semantic.

2. #### Non `Cloneable` implementation, but a new instance can be obtained
    A new instance can be obtained via reflection (e.g., plain, Objenesis), then we try to `putAll()` the `actual` elements
    * `putAll()` succeeds &#8594; we try to `remove()` the expected elements as in the `Cloneable` case.
    * `putAll()` fails with `UnsupportedOperationException`, (i.e., unmodifiable) &#8594; new `LinkedHashMap` is initialized with the elements of `actual`, `remove()` is repeated again &#8594;  unexpected elements are identified but with the potential loss of the original semantic.

3. #### No new instance can be obtained
    New `LinkedHashMap` is initialized with the elements of `actual`, the `remove()` of the expected elements is performed &#8594;  unexpected elements are identified but with the potential loss of the original semantic.

@joel-costigliola @filiphr what do you think about this approach? Do you see any other cases to be handled?

**Comment by joel-costigliola** [comment]
Sounds good to me, a few comments:

- `containsExactly` also checks the order of keys/entries 
- `IdentityHashMap` is another map implementation that does not rely on equals but being part of the JDK we could simply instantiate it directly.
- We would need to state in the javadoc that in some cases the key comparison semantics won't honored

**Comment by filiphr** [comment]
I think that your approach @scordio makes sense.

>`IdentityHashMap` is another map implementation that does not rely on equals but being part of the JDK we could simply instantiate it directly.

@joel-costigliola `IdentityHashMap` implements `Cloneable`. Therefore I think that it will be part of the first example from @scordio. I think that we should try and do as little key equal checks, which I think is being only done for `containsExactly`.

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 2]
```diff
@@ -670,15 +678,59 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
+      Class<? extends Map> type = map.getClass();
+      try {
+        // try with copying constructor
+        return type.getConstructor(Map.class).newInstance(map);
+      } catch (NoSuchMethodException e) {
+        // try with default constructor
+        Map<K, V> newMap = type.getConstructor().newInstance();
+        newMap.putAll(map);
+        return newMap;
+      }
```
Comment (scordio) [inline src/main/java/org/assertj/core/internal/Maps.java:728]: With this, I don't see the need of bringing in Objenesis. Please, let me know if you think otherwise.

Comment (joel-costigliola) [reply src/main/java/org/assertj/core/internal/Maps.java:728]: I agree we don't need objenesis for now

**Comment by scordio** [comment]
@joel-costigliola @filiphr `assertContainsOnly` and `assertContainsOnly` are in a reviewable shape, happy to get any feedback about the new implementation.

Most likely this PR will also include `assertContainsExactly`.

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 3]
```diff
@@ -370,15 +370,54 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
 
     if (!notFound.isEmpty() || !notExpected.isEmpty())
       throw failures.failure(info, shouldContainOnlyKeys(actual, keys, notFound, notExpected));
   }
 
+  private static <K> Set<K> getNotFoundKeys(Map<K, ?> actual, K[] keys) {
+    return Stream.of(keys)
+                 .filter(key -> !actual.containsKey(key))
+                 .collect(Collectors.toCollection(LinkedHashSet::new));
+  }
```
Comment (filiphr) [inline src/main/java/org/assertj/core/internal/Maps.java:384]: For performance reasons it is better to not use good old iterative style

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 4]
```diff
@@ -406,13 +445,40 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
     if (!notFound.isEmpty() || !notExpected.isEmpty())
       throw failures.failure(info, shouldContainOnly(actual, entries, notFound, notExpected));
   }
 
+  private static <K, V> Set<Entry<? extends K, ? extends V>> getNotFoundEntries(Map<K, V> actual,
+                                                                                Entry<? extends K, ? extends V>[] entries) {
+    return Stream.of(entries)
+                 .filter(entry -> !containsEntry(actual, entry))
+                 .collect(Collectors.toCollection(LinkedHashSet::new));
+  }
```
Comment (filiphr) [inline src/main/java/org/assertj/core/internal/Maps.java:459]: Same comment about the performance

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 5]
```diff
@@ -406,13 +445,40 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
+    try {
+      Map<K, V> clonedMap = clone(actual);
+      expectedEntries.forEach(entry -> clonedMap.remove(entry.getKey(), entry.getValue()));
+      return clonedMap;
+    } catch (NoSuchMethodException | UnsupportedOperationException e) {
+      // actual cannot be cloned or is unmodifiable, falling back to LinkedHashMap
+      Map<K, V> copiedMap = new LinkedHashMap<>(actual);
+      expectedEntries.forEach(entry -> copiedMap.remove(entry.getKey(), entry.getValue()));
+      return copiedMap;
+    }
```
Comment (filiphr) [inline src/main/java/org/assertj/core/internal/Maps.java:479]: For performance reasons it is better to use for loops instead of `.forEach`.

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 6]
```diff
@@ -441,27 +507,22 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
-    notExpected.addAll(actualEntries.keySet());
   }
 
   private <K, V> void compareActualMapAndExpectedEntries(Map<K, V> actual, Entry<? extends K, ? extends V>[] entries,
                                                          Set<Entry<? extends K, ? extends V>> notExpected,
                                                          Set<Entry<? extends K, ? extends V>> notFound) {
     Map<K, V> expectedEntries = entriesToMap(entries);
-    Map<K, V> actualEntries = new LinkedHashMap<>(actual);
+    Map<K, V> actualEntries = instantiate(actual.getClass());
+    actualEntries.putAll(actual);
```
Comment (filiphr) [inline src/main/java/org/assertj/core/internal/Maps.java:525]: Why not use `clone` here as well?

**Review by filiphr — COMMENTED** [review]
It looks great @scordio. Quite extensive tests and works as I would expect.

I've left some performance comments and one place where you used `instantiate` instead of `clone`.

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 6 above)
Comment (scordio) [reply src/main/java/org/assertj/core/internal/Maps.java:525]: This part is invoked only by `assertContainsExactly` that I still need to rework, once done it should disappear (and `clone` will be used)

**Comment by scordio** [comment]
Having the same pattern for `assertContainsExactly` will increase the complexity of this PR as the tests are more complicated due to the ordering requirement.

I will focus on `containsOnly` related assertions and update `assertContainsExactly` in a separate PR.

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 7]
```diff
@@ -370,15 +363,67 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
     if (!notFound.isEmpty() || !notExpected.isEmpty())
       throw failures.failure(info, shouldContainOnlyKeys(actual, keys, notFound, notExpected));
   }
 
+  private static <K> Set<K> getFoundKeys(Map<K, ?> actual, K[] expectedKeys) {
+    Set<K> found = new LinkedHashSet<>();
+    for (K expectedKey : expectedKeys) {
+      if (actual.containsKey(expectedKey)) found.add(expectedKey);
+    }
+    return found;
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/internal/Maps.java:378]: could use Stream API filter:
```java
return Stream.of(expectedKeys)
             .filter(actual::containsKey) 
             .collect(toCollection( LinkedHashSet::new));
```

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 8]
```diff
@@ -370,15 +363,67 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
+  }
+
+  private static <K> Set<K> getNotFoundKeys(Map<K, ?> actual, K[] expectedKeys) {
+    Set<K> notFound = new LinkedHashSet<>();
+    for (K expectedKey : expectedKeys) {
+      if (!actual.containsKey(expectedKey)) notFound.add(expectedKey);
+    }
+    return notFound;
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/internal/Maps.java:386]: similar comment here

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 9]
```diff
@@ -406,13 +451,48 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
       throw failures.failure(info, shouldContainOnly(actual, entries, notFound, notExpected));
   }
 
+  private static <K, V> Set<Entry<? extends K, ? extends V>> getNotFoundEntries(Map<K, V> actual,
+                                                                                Entry<? extends K, ? extends V>[] entries) {
+    Set<Entry<? extends K, ? extends V>> notFound = new LinkedHashSet<>();
+    for (Entry<? extends K, ? extends V> entry : entries) {
+      if (!containsEntry(actual, entry)) notFound.add(entry);
+    }
+    return notFound;
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/internal/Maps.java:467]: could  use stream api

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 10]
```diff
@@ -406,13 +451,48 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
+  }
+
+  private static <K, V> Set<Entry<K, V>> getNotExpectedEntries(Map<K, V> actual, Entry<? extends K, ? extends V>[] entries) {
+    Set<Entry<K, V>> notExpected = new LinkedHashSet<>();
+    for (Entry<K, V> entry : mapWithoutExpectedEntries(actual, entries).entrySet()) {
+      MapEntry<K, V> mapEntry = entry(entry.getKey(), entry.getValue());
+      notExpected.add(mapEntry);
+    }
+    return notExpected;
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/internal/Maps.java:476]: same comment

File: src/main/java/org/assertj/core/internal/Maps.java [hunk 11]
```diff
@@ -406,13 +451,48 @@ public void assertHasSameSizeAs(AssertionInfo info, Map<?, ?> map, Map<?, ?> oth
...
+  }
+
+  private static <K, V> Map<K, V> mapWithoutExpectedEntries(Map<K, V> actual, Entry<? extends K, ? extends V>[] expectedEntries) {
+    try {
+      Map<K, V> clonedMap = clone(actual);
+      for (Entry<? extends K, ? extends V> expectedEntry : expectedEntries) {
+        clonedMap.remove(expectedEntry.getKey(), expectedEntry.getValue());
+      }
+      return clonedMap;
+    } catch (NoSuchMethodException | UnsupportedOperationException e) {
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/internal/Maps.java:486]: should we also catch the `IllegalStateException` thrown by `clone(Map<K, V> map)`?

File: src/test/java/org/assertj/core/test/Maps.java [hunk 12]
```diff
@@ -24,18 +26,19 @@
...
-    return map;
+    return mapOf(LinkedHashMap::new, entries);
   }
 
   @SafeVarargs
   public static <K extends Comparable<? super K>, V> TreeMap<K, V> treeMapOf(MapEntry<K, V>... entries) {
-    TreeMap<K, V> map = new TreeMap<>();
-    for (MapEntry<K, V> entry : entries) {
-      map.put(entry.key, entry.value);
+    return mapOf(TreeMap::new, entries);
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/test/Maps.java:34]: nice, thanks!

**Review by joel-costigliola — COMMENTED** [review]
I still have to look at the tests but I thought I'll share my comments on the rest of the code

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 7 above)
Comment (scordio) [reply src/main/java/org/assertj/core/internal/Maps.java:378]: Initially, I used the Stream API but @filiphr correctly pointed out that the for loop would be better performance-wise. I seem to recall some issues about performance in case of big input, so the proposal seemed valid to me. What do you think about it?

File: src/main/java/org/assertj/core/api/AbstractMapAssert.java [hunk 13]
```diff
@@ -1136,7 +1136,10 @@ protected SELF doesNotContainKeysForProxy(K[] keys) {
 
   /**
    * Verifies that the actual map contains only the given keys and nothing else, in any order.
-   *
+   * <p>
+   * The verification tries to honor the key comparison semantic of the underlying map implementation, but there might
+   * be some cases where the semantic cannot be honored and not all the unexpected elements are identified correctly
+   * (e.g., due to immutability).
```
[the remark this answers is not in the document]
Comment (scordio) [reply src/main/java/org/assertj/core/api/AbstractMapAssert.java:1142]: What about:

> The verification tries to honor the key comparison semantic of the underlying map implementation. The map under test has to be cloned to identify unexpected elements, but depending on the map implementation this may not always be possible. In these cases, a regular map is used and the key comparison strategy may not be the same as the map under test.

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 11 above)
Comment (scordio) [reply src/main/java/org/assertj/core/internal/Maps.java:486]: I was wondering about the same.

Catching `IllegalStateException` (or even propagate the checked exceptions and catch them here) would make the assertion more robust.

On the other side, we may use `LinkedHashMap` for implementations that could be handled in a better way. I can imagine these would be exotic map implementations. It could be worth getting the knowledge about them and add proper tests.

Currently, I would take the risk, i.e., no catch for `IllegalStateException`.

File: src/main/java/org/assertj/core/util/Sets.java [hunk 14]
```diff
@@ -22,9 +22,22 @@
...
+   * Creates a <em>mutable</em> {@link HashSet} containing the given elements.
+   *
+   * @param <T> the generic type of the {@code HashSet} to create.
+   * @param elements the elements to store in the {@code HashSet}.
+   * @return the created {@code HashSet}, or {@code null} if the given array of elements is {@code null}.
+   */
+  @SafeVarargs
+  public static <T> Set<T> set(T... elements) {
+    return newLinkedHashSet(elements);
+  }
```
Comment (scordio) [inline src/main/java/org/assertj/core/util/Sets.java:39]: Perhaps I should highlight this addition in the util class, which would be publicly available. Let me know if you have any problems with it.

File: src/main/java/org/assertj/core/api/AbstractMapAssert.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (joel-costigliola) [reply src/main/java/org/assertj/core/api/AbstractMapAssert.java:1142]: sounds good to me

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 7 above)
Comment (joel-costigliola) [reply src/main/java/org/assertj/core/internal/Maps.java:378]: fair enough, let's add a comment saying we don't use stream for performance reasons.

File: src/main/java/org/assertj/core/internal/Maps.java (hunk 11 above)
Comment (joel-costigliola) [reply src/main/java/org/assertj/core/internal/Maps.java:486]: fine by me

File: src/main/java/org/assertj/core/util/Sets.java (hunk 14 above)
Comment (joel-costigliola) [reply src/main/java/org/assertj/core/util/Sets.java:39]: we can but for me these util classes are not meant to be API so we don't need to publicize them.

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java [hunk 15]
```diff
@@ -12,112 +12,216 @@
...
+
+  @SuppressWarnings("unchecked")
+  private static final Supplier<Map<String, String>>[] CASE_INSENSITIVE_MAPS = new Supplier[] {
+      // org.apache.commons.collections4.map.CaseInsensitiveMap not included due to slightly different behavior
+      LinkedCaseInsensitiveMap::new,
+      CASE_INSENSITIVE_TREE_MAP
+  };
+
+  @SuppressWarnings("unchecked")
+  private static final Supplier<Map<String, String>>[] MODIFIABLE_MAPS = ArrayUtils.addAll(CASE_INSENSITIVE_MAPS,
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:75]: just curious why not using `new Supplier[]` as in L68

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java [hunk 16]
```diff
@@ -12,112 +12,216 @@
...
-  @Test
-  void should_pass_if_actual_contains_only_expected_keys() {
-    maps.assertContainsOnlyKeys(someInfo(), actual, array("color", "name"));
-    maps.assertContainsOnlyKeys(someInfo(), actual, array("name", "color"));
+  private static Stream<Arguments> unmodifiableMapsSuccessfulTestCases() {
+    return Stream.of(arguments(Collections.emptyMap(), emptyKeys()),
+                     arguments(Collections.singletonMap("name", "Yoda"), array("name")),
+                     arguments(new SingletonMap<>("name", "Yoda"), array("name")),
+                     arguments(Collections.unmodifiableMap(mapOf(entry("name", "Yoda"), entry("job", "Jedi"))),
+                               array("name", "job")),
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:130]: minor: we don't loose information by static import `Collections.` and that will make the code a bit lighter.

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java [hunk 17]
```diff
@@ -12,112 +12,216 @@
...
+                     arguments(ImmutableMap.of("name", "Yoda", "job", "Jedi"), array("name", "job")));
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:131]: keep the static import here, if we don't it's not clear a map is being built.

Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:131]: add `arguments(ImmutableMap.of("name", "Yoda", "job", "Jedi"), array("job", "name"))` as in `modifiableMapsSuccessfulTestCases`

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java [hunk 18]
```diff
@@ -12,112 +12,216 @@
...
-    // WHEN
-    expectAssertionError(() -> maps.assertContainsOnlyKeys(info, underTest, expectedKeys));
-    // THEN
-    verify(failures).failure(info, shouldContainOnlyKeys(underTest, expectedKeys, set("color"), emptySet()));
+  private static Stream<Arguments> caseInsensitiveMapsSuccessfulTestCases() {
+    return Stream.of(ArrayUtils.add(CASE_INSENSITIVE_MAPS, CaseInsensitiveMap::new))
+                 .flatMap(supplier -> Stream.of(arguments(mapOf(supplier, entry("NAME", "Yoda"), entry("Job", "Jedi")),
+                                                          array("name", "job")),
+                                                arguments(mapOf(supplier, entry("NAME", "Yoda"), entry("Job", "Jedi")),
+                                                          array("Name", "Job"))));
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:147]: invert the order to show order is not important or add another `arguments` with the inverted order.

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java [hunk 19]
```diff
@@ -12,112 +12,216 @@
...
+    then(error).as(actual.getClass().getName())
+               .hasMessage(shouldContainOnlyKeys(actual, expected, notFound, notExpected).create());
   }
 
-  private static HashSet<String> set(String entry) {
-    HashSet<String> set = new HashSet<>();
-    set.add(entry);
-    return set;
+  private static Stream<Arguments> unmodifiableMapsFailureTestCases() {
+    return Stream.of(arguments(Collections.emptyMap(),
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:166]: similar comment for static import.

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnly_Test.java [hunk 20]
```diff
@@ -12,131 +12,225 @@
...
+  void should_pass(Map<String, String> actual, Entry<String, String>[] expected) {
+    // WHEN/THEN
+    assertThatNoException().as(actual.getClass().getName())
+                           .isThrownBy(() -> maps.assertContainsOnly(info, actual, expected));
   }
 
-  @Test
-  void should_pass_if_actual_contains_only_expected_entries() {
-    maps.assertContainsOnly(someInfo(), actual, array(entry("name", "Yoda"), entry("color", "green")));
+  private static Stream<Arguments> unmodifiableMapsSuccessfulTestCases() {
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnly_Test.java:122]: similar comment on static import

File: src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java [hunk 21]
```diff
@@ -71,7 +78,7 @@ void should_fail_if_actual_contains_key() {
     Throwable error = catchThrowable(() -> maps.assertDoesNotContainKeys(info, actual, new String[] { key }));
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java:78]: use `expectAssertionError` to remove `assertThat(error).isInstanceOf(AssertionError.class);` and `error` local variable

File: src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java [hunk 22]
```diff
@@ -83,6 +90,6 @@ void should_fail_if_actual_contains_keys() {
     Throwable error = catchThrowable(() -> maps.assertDoesNotContainKeys(info, actual, new String[] { key1, key2 }));
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java:90]: same comment here

**Review by joel-costigliola — COMMENTED** [review]
just some minor code cleanup and we are good to go!

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java (hunk 18 above)
Comment (scordio) [reply src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:147]: Test cases added

File: src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java (hunk 15 above)
Comment (scordio) [reply src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java:77]: Because I want to concatenate the existing `CASE_INSENSITIVE_MAPS` with the additional case-sensitive suppliers: if we add anything new to the former, all the test cases for `MODIFIABLE_MAPS` should run and pass out of the box.

File: src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java (hunk 21 above)
Comment (joel-costigliola) [reply src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java]: not sure why you resolved this one @scordio ;-)

Comment (scordio) [reply src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java]: Becase I rewrote the entire `Maps_assertDoesNotContainKeys_Test` 🙂

**Comment by joel-costigliola** [comment]
Thanks @filiphr and @scordio, this is now integrated.
